jobs:
  include:
    - stage: Test
      language: python
      python: 3.9
      name: Unit Test Job 
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
      script:
        - pytest
        - python hello.py 
    
    - if: branch = "dev"
    - stage: Dev Run
      env: 
        STAGE=dev
      language: node_js
      node_js: stable 
      before_install:
        - npm install gulp-cli 
      script:
        - gulp --version
    - if: branch = "staging"
    - stage: Staging Run
      env: 
        STAGE=staging
      language: node_js
      node_js: stable 
      before_install:
        - npm install gulp-cli 
      script:
        - gulp --version
    - if: branch = "master"
    - stage: Master Run
      env: 
        STAGE=master
      language: node_js
      node_js: stable 
      before_install:
        - npm install gulp-cli 
      script:
        - gulp --version
         
    

      
